name: muse_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  flutter_gemini: ^2.0.3
  go_router: ^13.2.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  retrofit: ^4.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
  

  assets:
    - .env
    - assets/logo/
    - assets/onboard/